name: GoDoc on GitHub Pages

on:
  push: [main]
  pull_request: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
