name: Test

on: [push, pull_request]

jobs:
  main:
    name: Test Unit
    strategy:
      matrix:
        go-version: [1.14.x]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@v0.5.0
        with:
          test-results: test.json
